/** @type {import('tailwindcss').Config} */
const rgb = (name) => `rgb(var(${name}) / <alpha-value>)`

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: rgb('--tw-bg'),
        foreground: rgb('--tw-fg'),
        line: rgb('--tw-line'),
        elevated: rgb('--tw-bg-elevated'),
        nav: rgb('--tw-nav'),
        'on-nav': rgb('--tw-on-nav'),

        surface: rgb('--tw-surface'),
        'surface-dim': rgb('--tw-surface-dim'),
        'surface-bright': rgb('--tw-surface-bright'),
        'surface-variant': rgb('--tw-surface-variant'),
        'surface-container': rgb('--tw-surface-container'),
        'surface-container-low': rgb('--tw-surface-container-low'),
        'surface-container-high': rgb('--tw-surface-container-high'),
        'surface-container-highest': rgb('--tw-surface-container-highest'),
        'surface-container-lowest': rgb('--tw-surface-container-lowest'),
        'surface-tint': rgb('--tw-surface-tint'),

        'on-background': rgb('--tw-fg'),
        'on-surface': rgb('--tw-fg'),
        'on-surface-variant': rgb('--tw-fg-muted'),

        primary: rgb('--tw-primary'),
        'on-primary': rgb('--tw-on-primary'),
        'primary-container': rgb('--tw-primary-container'),
        'on-primary-container': rgb('--tw-on-primary-container'),
        'primary-fixed': rgb('--tw-primary'),
        'primary-fixed-dim': rgb('--tw-primary-container'),
        'on-primary-fixed': rgb('--tw-on-primary'),
        'on-primary-fixed-variant': rgb('--tw-fg-muted'),
        'inverse-primary': rgb('--tw-inverse-primary'),

        secondary: rgb('--tw-secondary'),
        'on-secondary': rgb('--tw-on-secondary'),
        'secondary-container': rgb('--tw-secondary'),
        'on-secondary-container': rgb('--tw-on-secondary'),
        'secondary-fixed': rgb('--tw-secondary'),
        'secondary-fixed-dim': rgb('--tw-secondary'),
        'on-secondary-fixed': rgb('--tw-on-primary'),
        'on-secondary-fixed-variant': rgb('--tw-fg-muted'),

        tertiary: rgb('--tw-tertiary'),
        'on-tertiary': rgb('--tw-on-tertiary'),
        'tertiary-container': rgb('--tw-tertiary'),
        'on-tertiary-container': rgb('--tw-on-tertiary'),
        'tertiary-fixed': rgb('--tw-tertiary'),
        'tertiary-fixed-dim': rgb('--tw-tertiary-dim'),
        'on-tertiary-fixed': rgb('--tw-fg'),
        'on-tertiary-fixed-variant': rgb('--tw-fg-muted'),

        outline: rgb('--tw-outline'),
        'outline-variant': rgb('--tw-outline-variant'),

        error: rgb('--tw-error'),
        'on-error': rgb('--tw-on-error'),
        'error-container': rgb('--tw-error-container'),
        'on-error-container': rgb('--tw-on-error-container'),

        'inverse-surface': rgb('--tw-inverse-surface'),
        'inverse-on-surface': rgb('--tw-inverse-on-surface'),

        /* Status pills (solid + text) */
        'status-active-bg': rgb('--tw-success-bg'),
        'status-active-fg': rgb('--tw-success-fg'),
        'status-pending-bg': rgb('--tw-warning-bg'),
        'status-pending-fg': rgb('--tw-warning-fg'),
        'status-done-bg': rgb('--tw-done-bg'),
        'status-done-fg': rgb('--tw-done-fg'),
        'status-info-bg': rgb('--tw-info-bg'),
        'status-info-fg': rgb('--tw-info-fg'),
      },
      boxShadow: {
        card: 'var(--tw-card-shadow)',
        'card-hover': 'var(--tw-card-shadow-hover)',
        'focus-ring': '0 0 0 3px rgba(27, 58, 107, 0.12)',
        'cyan-glow': '0 8px 24px rgba(6, 182, 212, 0.25)',
        'primary-glow': '0 10px 28px rgba(27, 58, 107, 0.28)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        margin: '32px',
        base: '4px',
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        '2xl': '4rem',
        lg: '1.5rem',
        gutter: '24px',
        xl: '2.5rem',
      },
      fontFamily: {
        sans: ['Sora', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
        'label-md': ['Sora', 'system-ui', 'sans-serif'],
        'headline-xl': ['Sora', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'system-ui', 'sans-serif'],
        'headline-md': ['Sora', 'system-ui', 'sans-serif'],
        'label-sm': ['Sora', 'system-ui', 'sans-serif'],
        'body-lg': ['Sora', 'system-ui', 'sans-serif'],
        'body-sm': ['Sora', 'system-ui', 'sans-serif'],
        'body-md': ['Sora', 'system-ui', 'sans-serif'],
        'headline-lg': ['Sora', 'system-ui', 'sans-serif'],
        'headline-sm': ['Sora', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '700' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.5px', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.5px', fontWeight: '800' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.5px', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '450' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '450' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.5px', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.5px', fontWeight: '800' }],
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        blob: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(12px, -18px) scale(1.04)' },
          '66%': { transform: 'translate(-10px, 10px) scale(0.98)' },
        },
        pulseDot: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(0.85)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.55s ease-out both',
        blob: 'blob 18s ease-in-out infinite',
        'pulse-dot': 'pulseDot 1.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
