/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#001f26',
        'tertiary-fixed-dim': '#4cd7f6',
        'surface-container-low': '#171c27',
        'inverse-on-surface': '#2b303c',
        'primary-fixed': '#d8e2ff',
        'error-container': '#93000a',
        'surface-tint': '#adc6ff',
        'surface-container-high': '#252a35',
        'on-secondary': '#3c0091',
        'surface-dim': '#0e131e',
        'tertiary-container': '#009eb9',
        surface: '#0e131e',
        'surface-variant': '#303541',
        'on-tertiary': '#003640',
        'surface-container-highest': '#303541',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        tertiary: '#4cd7f6',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'surface-container-lowest': '#090e19',
        background: '#0e131e',
        'inverse-surface': '#dee2f2',
        'secondary-container': '#571bc1',
        'primary-container': '#4d8eff',
        'outline-variant': '#424754',
        'inverse-primary': '#005ac2',
        'on-tertiary-fixed-variant': '#004e5c',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#00285d',
        error: '#ffb4ab',
        secondary: '#d0bcff',
        'secondary-fixed-dim': '#d0bcff',
        'on-tertiary-container': '#002f38',
        'on-primary-fixed-variant': '#004395',
        'on-secondary-fixed': '#23005c',
        'surface-bright': '#343945',
        'on-secondary-fixed-variant': '#5516be',
        outline: '#8c909f',
        'on-background': '#dee2f2',
        'on-surface-variant': '#c2c6d6',
        'surface-container': '#1b202b',
        'tertiary-fixed': '#acedff',
        'on-surface': '#dee2f2',
        'secondary-fixed': '#e9ddff',
        'on-secondary-container': '#c4abff',
        'on-error': '#690005',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '32px',
        base: '4px',
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        '2xl': '4rem',
        lg: '1.5rem',
        gutter: '24px',
        xl: '2.5rem',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}
